# Generated by Django 4.2.1 on 2023-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_credential_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="url",
            field=models.URLField(),
        ),
    ]
