# Generated by Django 4.2.1 on 2023-06-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_credential_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
