# Generated by Django 4.2.1 on 2023-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_credential_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="show_password",
            field=models.BooleanField(default=False),
        ),
    ]
