# Generated by Django 4.2.1 on 2023-06-09 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_credential_show_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credential",
            name="show_password",
        ),
    ]
