# Generated by Django 4.2.1 on 2023-06-09 14:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_remove_credential_show_password"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sharedcredential",
            unique_together={("credential", "user_to")},
        ),
    ]
